name: widgets
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_spinkit: ^4.1.2+1
  values:
    path: ../../libraries/values
  core:
    path: ../../libraries/core

dev_dependencies:
  flutter_test:
    sdk: flutter
